[paths]
content_dir = "/tmp/lst-test-content"
media_dir = "media"
kinds = ["lists", "notes", "posts"]

[auth]
jwt_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYW5zQHRlc3QuZGUiLCJleHAiOjE3NTUwMTQ0MTV9.H0E2mdCAYL0I4MFHY_s1KtMMq-gT5Q6-cWxGzUFc1_s"
jwt_expires_at = "2025-08-03T21:31:02.796376Z"

[server]
jwt_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYW5zQHRlc3QuZGUiLCJleHAiOjE3NTUwMTQ0MTV9.H0E2mdCAYL0I4MFHY_s1KtMMq-gT5Q6-cWxGzUFc1_s"
jwt_expires_at = "2025-08-03T21:31:02.796376Z"
host = "0.0.0.0"

[syncd]
url = "ws://192.168.1.25:5673/api/sync"
device_id = "desktop-syncd-device-001"
database_path = "/tmp/desktop-sync.db"
encryption_key_ref = "/tmp/desktop-sync.key"

[sync]
server_url = "ws://192.168.1.25:5673/api/sync"
interval_seconds = 30
max_file_size = 10485760
exclude_patterns = []