# Example lst configuration with custom themes directory

[paths]
# Custom themes directory (defaults to ~/.config/themes if not specified)
themes_dir = "/path/to/your/custom/themes"

# Other path configurations
content_dir = "~/Documents/lst"
media_dir = "~/Documents/lst/media"

[ui]
# Enable vim mode
vim_mode = true
leader_key = " "

# Example theme configuration (optional - can be set via CLI)
# This will be the default theme when the app starts
[[theme]]
scheme = "base16-catppuccin-latte"
name = "Catppuccin Latte"
system = "base16"
variant = "light"

# You can also override specific colors
[theme.overrides]
base00 = "#f5f5f5"  # Custom background color

[server]
url = "https://your-lst-server.com"