# Complete configuration example for lst
# Place at ~/.config/lst/lst.toml (user config).
# Runtime state and secrets are stored in ~/.local/share/lst/state.toml and
# are managed by the app; do not put secrets in this file.
# All sections are optional and will use defaults if not specified.

# =============================================================================
# UI Configuration (Desktop/Mobile Apps)
# =============================================================================
[ui]
# Order for resolving list/note names (first match wins)
# Options: "anchor", "exact", "fuzzy", "index", "interactive"
resolution_order = [
  "anchor",      # Match items with anchor tags (#tag)
  "exact",       # Exact string match
  "fuzzy",       # Fuzzy string matching
  "index",       # Match by numeric index
  "interactive", # Interactive selection prompt
]

# Enable Vim-style keyboard navigation in the desktop app
vim_mode = false

# Leader key for command sequences (defaults to space)
leader_key = " "

# Optional theme overrides. Keys correspond to CSS variables defined by the app.
# When omitted, the built-in theme is used.
[ui.theme.vars]
# background = "#24273a"
# foreground = "#cad3f5"
# primary = "#8aadf4"
# secondary = "#f4dbd6"
# accent = "#c6a0f6"
# muted = "#5b6078"
# border = "#494d64"
# radius = "0.625rem"

# =============================================================================
# Fuzzy Search Configuration
# =============================================================================
[fuzzy]
# Threshold for fuzzy matching (0.0 = accept all, 1.0 = exact match only)
threshold = 0.75

# Maximum number of suggestions to show
max_suggestions = 7

# =============================================================================
# Path Configuration (Shared by all components)
# =============================================================================
[paths]
# Root directory for all content (lists, notes, posts)
# Supports ~ for home directory expansion
content_dir = "~/Documents/lst-content"
# Alternative: absolute path
# content_dir = "/Users/username/Documents/lst-content"

# Subdirectory for media files (relative to content_dir)
media_dir = "media"

# Document types to recognize
kinds = ["lists", "notes", "posts"]

# Directory containing theme files (defaults to ~/.config/themes)
# Supports tinty-compatible base16/base24 theme structure
# themes_dir = "~/my-custom-themes"

# =============================================================================
# Server Daemon Configuration (lst-server only)
# =============================================================================
# Note: These are server runtime storage paths (state) used by the daemon.
[server]
# Network interface to bind to
host = "127.0.0.1" # localhost only
# host = "0.0.0.0"   # all interfaces

# Port to listen on
port = 5673

# Database configuration for lst-server daemon
# (runtime state; not user content)
data_dir = "~/.config/lst/lst_server_data"
# Alternative: absolute path
# data_dir = "/var/lib/lst"

# Individual database file names (relative to data_dir unless absolute)
# (runtime state files)
tokens_db = "tokens.db"   # User authentication tokens
content_db = "content.db" # Content storage
sync_db = "sync.db"       # CRDT sync data

# =============================================================================
# Email Configuration (lst-server only)
# =============================================================================
[email]
# SMTP server hostname
smtp_host = "smtp.gmail.com"

# SMTP username
smtp_user = "your-email@gmail.com"

# SMTP password (can use environment variable)
smtp_pass = "${SMTP_PASSWORD}" # reads from environment variable
# Alternative: direct password (not recommended for production)
# smtp_pass = "your-app-password"

# From address for sent emails
sender = "lst-server@yourdomain.com"

# =============================================================================
# Client Sync Configuration (lst CLI, lst-syncd, apps)
# =============================================================================
# Note: Only user-configurable settings belong here. Runtime state and secrets
# are stored in ~/.local/share/lst/state.toml and managed by the app.
[sync]
# Server for syncing (if None, runs in local-only mode)
# Simple format: "host:port" (recommended)
server_url = "192.168.1.25:5673"
# Alternative: full WebSocket URL
# server_url = "ws://192.168.1.25:5673/api/sync"

# How often to check for changes (in seconds)
interval_seconds = 30

# Maximum file size to sync (in bytes, 10MB default)
max_file_size = 10485760

# File patterns to exclude from syncing
exclude_patterns = [
  ".*",              # Hidden files
  "*.tmp",           # Temporary files
  "*.swp",           # Vim swap files
  "*.bak",           # Backup files
  "*~",              # Emacs backup files
  "node_modules/**", # Node.js dependencies
  ".git/**",         # Git repository data
  "*.log",           # Log files
  "Thumbs.db",       # Windows thumbnail cache
  ".DS_Store",       # macOS folder metadata
]

# Managed by app state (do not set here):
# auth_token = "..."           # stored in ~/.local/share/lst/state.toml
# jwt_token = "..."            # stored in state.toml
# jwt_expires_at = "..."       # stored in state.toml
# device_id = "..."            # stored in state.toml
# database_path = "..."        # defaults to ~/.local/share/lst/sync.db (state)
# encryption_key_ref = "..."   # reference name; key material lives in keychain

# =============================================================================
# Storage Configuration (CRDT storage for sync)
# =============================================================================
[storage]
# Directory for CRDT (Conflict-free Replicated Data Type) storage
crdt_dir = "~/.config/lst/crdt"

# Maximum number of snapshots to retain
max_snapshots = 100

# =============================================================================
# Example Production Server Configuration
# =============================================================================
# Uncomment and modify for production deployment:
#
# [server]
# host = "0.0.0.0"
# port = 8080
# data_dir = "/var/lib/lst"
# tokens_db = "tokens.db"
# content_db = "content.db"
# sync_db = "sync.db"
#
# [email]
# smtp_host = "smtp.sendgrid.net"
# smtp_user = "apikey"
# smtp_pass = "${SENDGRID_API_KEY}"
# sender = "noreply@yourdomain.com"
#
# [paths]
# content_dir = "/var/lib/lst/content"
# media_dir = "media"
# kinds = ["lists", "notes", "posts"]
#
# [sync]
# server_url = "wss://lst.yourdomain.com/api/sync"
# interval_seconds = 60

# =============================================================================
# Example Development Configuration
# =============================================================================
# For local development and testing:
#
# [paths]
# content_dir = "~/dev/lst-test-content"
#
# [server]
# host = "127.0.0.1"
# port = 5673
# data_dir = "~/.config/lst/dev_data"
#
# [sync]
# server_url = "ws://localhost:5673/api/sync"
# interval_seconds = 5  # More frequent sync for development