[package]
name = "lst-proto"
version = "0.1.0"
description = "Shared types and protocol definitions for lst"
authors = ["Tommy Falkowski"]
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }